Make 'xwalk_application_lib' target explicitly depend on 'events.gyp:events'
This fixes the following error, when buiding with crosswalk-bin.spec:

[XXs] xwalk/application/browser/application_tizen.cc:317:
  error: undefined reference to 'ui::EventFromNative(void* const&)'